'use client';

import { useState, useEffect } from 'react';
import { useLanguage } from '@/context/LanguageContext';

export const staticDictionary: { [key: string]: { [key: string]: string } } = {
  'Menü': { 'en': 'Menu', 'de': 'Menü', 'tr': 'Menü', 'ar': 'قائمة', 'ru': 'Меню', 'fr': 'Menu', 'es': 'Menú', 'it': 'Menu' },
  'Sepet': { 'en': 'Cart', 'de': 'Warenkorb', 'tr': 'Sepet', 'ar': 'سلة', 'ru': 'Корзина', 'fr': 'Panier', 'es': 'Carrito', 'it': 'Carrello' },
  'Garson Çağır': { 'en': 'Call Waiter', 'de': 'Kellner rufen', 'tr': 'Garson Çağır', 'ar': 'نداء النادل', 'ru': 'Вызов официанта', 'fr': 'Appeler serveur', 'es': 'Llamar camarero', 'it': 'Chiama cameriere' },
  'Detayları Gör': { 'en': 'View Details', 'de': 'Details', 'tr': 'Detayları Gör', 'ar': 'عرض التفاصيل', 'ru': 'Подробнее', 'fr': 'Voir détails', 'es': 'Ver detalles', 'it': 'Vedi dettagli' },
  'Sepete Ekle': { 'en': 'Add to Cart', 'de': 'In den Warenkorb', 'tr': 'Sepete Ekle', 'ar': 'أضف إلى السلة', 'ru': 'В корзину', 'fr': 'Ajouter', 'es': 'Añadir', 'it': 'Aggiungi' },
  'Popüler': { 'en': 'Popular', 'de': 'Beliebt', 'tr': 'Popüler', 'ar': 'شائع', 'ru': 'Популярное', 'fr': 'Populaire', 'es': 'Popular', 'it': 'Popolare' },
  'Menüde ara...': { 'en': 'Search menu...', 'de': 'Menü durchsuchen...', 'tr': 'Menüde ara...', 'ar': 'بحث في القائمة...', 'ru': 'Поиск по меню...', 'fr': 'Rechercher...', 'es': 'Buscar...', 'it': 'Cerca...' },
  'WiFi Şifresi': { 'en': 'WiFi Password', 'de': 'WLAN-Passwort', 'tr': 'WiFi Şifresi', 'ar': 'كلمة مرور WiFi', 'ru': 'Пароль WiFi', 'fr': 'Mot de passe WiFi', 'es': 'Contraseña WiFi', 'it': 'Password WiFi' },
  "Google'da Değerlendir": { 'en': 'Rate on Google', 'de': 'Auf Google bewerten', 'tr': "Google'da Değerlendir", 'ar': 'قيم على جوجل', 'ru': 'Оценить в Google', 'fr': 'Évaluer sur Google', 'es': 'Calificar en Google', 'it': 'Valuta su Google' },
  'Yorum Yap': { 'en': 'Review', 'de': 'Bewerten', 'tr': 'Yorum Yap', 'ar': 'مراجعة', 'ru': 'Отзыв', 'fr': 'Avis', 'es': 'Reseña', 'it': 'Recensione' },
  'Çalışma Saatleri': { 'en': 'Working Hours', 'de': 'Öffnungszeiten', 'tr': 'Çalışma Saatleri', 'ar': 'ساعات العمل', 'ru': 'Часы работы', 'fr': 'Heures ouverture', 'es': 'Horario', 'it': 'Orari' },
  "Instagram'da Takip Et": { 'en': 'Follow on Instagram', 'de': 'Auf Instagram folgen', 'tr': "Instagram'da Takip Et", 'ar': 'تابع على انستغرام', 'ru': 'Instagram', 'fr': 'Suivre Instagram', 'es': 'Seguir Instagram', 'it': 'Segui Instagram' },
  'WiFi Password': { 'en': 'WiFi Password', 'de': 'WLAN-Passwort', 'tr': 'WiFi Şifresi', 'ar': 'كلمة مرور WiFi', 'ru': 'Пароль WiFi', 'fr': 'Mot de passe WiFi', 'es': 'Contraseña WiFi', 'it': 'Password WiFi' },
  // Cart Page Terms
  'Sepetiniz boş': { 'en': 'Your cart is empty', 'de': 'Ihr Warenkorb ist leer', 'tr': 'Sepetiniz boş', 'ar': 'سلة التسوق فارغة', 'ru': 'Ваша корзина пуста', 'fr': 'Votre panier est vide', 'es': 'Tu carrito está vacío', 'it': 'Il tuo carrello è vuoto' },
  'Menüden ürün ekleyerek başlayın': { 'en': 'Start by adding items from the menu', 'de': 'Beginnen Sie mit dem Hinzufügen von Artikeln aus dem Menü', 'tr': 'Menüden ürün ekleyerek başlayın', 'ar': 'ابدأ بإضافة عناصر من القائمة', 'ru': 'Начните с добавления блюд из меню', 'fr': 'Commencez par ajouter des articles du menu', 'es': 'Empieza añadiendo artículos del menú', 'it': 'Inizia aggiungendo articoli dal menu' },
  'Menüye Git': { 'en': 'Go to Menu', 'de': 'Zum Menü', 'tr': 'Menüye Git', 'ar': 'الذهاب للقائمة', 'ru': 'Перейти в меню', 'fr': 'Aller au menu', 'es': 'Ir al menú', 'it': 'Vai al menu' },
  'Ödeme Seçenekleri': { 'en': 'Payment Options', 'de': 'Zahlungsmöglichkeiten', 'tr': 'Ödeme Seçenekleri', 'ar': 'خيارات الدفع', 'ru': 'Варианты оплаты', 'fr': 'Options de paiement', 'es': 'Opciones de pago', 'it': 'Opzioni di pagamento' },
  'Kart': { 'en': 'Card', 'de': 'Karte', 'tr': 'Kart', 'ar': 'بطاقة', 'ru': 'Карта', 'fr': 'Carte', 'es': 'Tarjeta', 'it': 'Carta' },
  'Nakit': { 'en': 'Cash', 'de': 'Bar', 'tr': 'Nakit', 'ar': 'نقدي', 'ru': 'Наличные', 'fr': 'Espèces', 'es': 'Efectivo', 'it': 'Contanti' },
  'Garsona Bahşiş': { 'en': 'Tip to Waiter', 'de': 'Trinkgeld', 'tr': 'Garsona Bahşiş', 'ar': 'بقشيش للنادل', 'ru': 'Чаевые официанту', 'fr': 'Pourboire', 'es': 'Propina', 'it': 'Mancia al cameriere' },
  'Bağış Yap': { 'en': 'Donate', 'de': 'Spenden', 'tr': 'Bağış Yap', 'ar': 'تبرع', 'ru': 'Пожертвовать', 'fr': 'Faire un don', 'es': 'Donar', 'it': 'Fai una donazione' },
  'Sipariş Özeti': { 'en': 'Order Summary', 'de': 'Bestellübersicht', 'tr': 'Sipariş Özeti', 'ar': 'ملخص الطلب', 'ru': 'Сводка заказа', 'fr': 'Résumé de la commande', 'es': 'Resumen del pedido', 'it': 'Riepilogo ordine' },
  'Ara Toplam': { 'en': 'Subtotal', 'de': 'Zwischensumme', 'tr': 'Ara Toplam', 'ar': 'المجموع الفرعي', 'ru': 'Подитог', 'fr': 'Sous-total', 'es': 'Subtotal', 'it': 'Totale parziale' },
  'Bahşiş': { 'en': 'Tip', 'de': 'Gesamt', 'tr': 'Bahşiş', 'ar': 'بقشيش', 'ru': 'Чаевые', 'fr': 'Pourboire', 'es': 'Propina', 'it': 'Mancia' },
  'Bağış': { 'en': 'Donation', 'de': 'Spende', 'tr': 'Bağış', 'ar': 'تبرع', 'ru': 'Пожертвование', 'fr': 'Don', 'es': 'Donación', 'it': 'Donazione' },
  'Toplam': { 'en': 'Total', 'de': 'Gesamt', 'tr': 'Toplam', 'ar': 'المجموع', 'ru': 'Итого', 'fr': 'Total', 'es': 'Total', 'it': 'Totale' },
  'Ödemeyi Tamamla': { 'en': 'Complete Payment', 'de': 'Zahlung abschließen', 'tr': 'Ödemeyi Tamamla', 'ar': 'إتمام الدفع', 'ru': 'Завершить оплату', 'fr': 'Payer', 'es': 'Completar pago', 'it': 'Completa pagamento' },
  'Ödeme Onayı': { 'en': 'Payment Confirmation', 'de': 'Zahlungsbestätigung', 'tr': 'Ödeme Onayı', 'ar': 'تأكيد الدفع', 'ru': 'Подтверждение оплаты', 'fr': 'Confirmation de paiement', 'es': 'Confirmación de pago', 'it': 'Conferma pagamento' },
  'Toplam Tutar:': { 'en': 'Total Amount:', 'de': 'Gesamtbetrag:', 'tr': 'Toplam Tutar:', 'ar': 'المبلغ الإجمالي:', 'ru': 'Общая сумма:', 'fr': 'Montant total :', 'es': 'Importe total:', 'it': 'Importo totale:' },
  'İptal': { 'en': 'Cancel', 'de': 'Abbrechen', 'tr': 'İptal', 'ar': 'إلغاء', 'ru': 'Отмена', 'fr': 'Annuler', 'es': 'Cancelar', 'it': 'Annulla' },
  'Öde': { 'en': 'Pay', 'de': 'Bezahlen', 'tr': 'Öde', 'ar': 'دفع', 'ru': 'Оплатить', 'fr': 'Payer', 'es': 'Pagar', 'it': 'Paga' },
  'Bahşiş Miktarı': { 'en': 'Tip Amount', 'de': 'Trinkgeldbetrag', 'tr': 'Bahşiş Miktarı', 'ar': 'مبلغ الإكرامية', 'ru': 'Сумма чаевых', 'fr': 'Montant du pourboire', 'es': 'Monto de propina', 'it': 'Importo mancia' },
  'Hızlı Seçim': { 'en': 'Quick Select', 'de': 'Schnellauswahl', 'tr': 'Hızlı Seçim', 'ar': 'تحديد سريع', 'ru': 'Быстрый выбор', 'fr': 'Sélection rapide', 'es': 'Selección rápida', 'it': 'Selezione rapida' },
  'Manuel Miktar': { 'en': 'Manual Amount', 'de': 'Manueller Betrag', 'tr': 'Manuel Miktar', 'ar': 'مبلغ يدوي', 'ru': 'Ручной ввод', 'fr': 'Montant manuel', 'es': 'Monto manual', 'it': 'Importo manuale' },
  'Tamam': { 'en': 'OK', 'de': 'OK', 'tr': 'Tamam', 'ar': 'موافق', 'ru': 'ОК', 'fr': 'OK', 'es': 'OK', 'it': 'OK' },
  'Bağış Miktarı': { 'en': 'Donation Amount', 'de': 'Spendenbetrag', 'tr': 'Bağış Miktarı', 'ar': 'مبلغ التبرع', 'ru': 'Сумма пожертвования', 'fr': 'Montant du don', 'es': 'Monto de donación', 'it': 'Importo donazione' },
  // Call Waiter Page Terms
  'Masa Numaranız': { 'en': 'Your Table Number', 'de': 'Ihre Tischnummer', 'tr': 'Masa Numaranız', 'ar': 'رقم طاولتك', 'ru': 'Ваш номер стола', 'fr': 'Votre numéro de table', 'es': 'Tu número de mesa', 'it': 'Il tuo numero di tavolo' },
  'Hızlı İstekler': { 'en': 'Quick Requests', 'de': 'Schnellanfragen', 'tr': 'Hızlı İstekler', 'ar': 'طلبات سريعة', 'ru': 'Быстрые запросы', 'fr': 'Demandes rapides', 'es': 'Solicitudes rápidas', 'it': 'Richieste rapide' },
  'Su Getir': { 'en': 'Bring Water', 'de': 'Wasser bringen', 'tr': 'Su Getir', 'ar': 'إحضر ماء', 'ru': 'Принести воды', 'fr': 'Apporter de l\'eau', 'es': 'Traer agua', 'it': 'Porta acqua' },
  'Hesap İste': { 'en': 'Ask for Bill', 'de': 'Rechnung bitten', 'tr': 'Hesap İste', 'ar': 'طلب الفاتورة', 'ru': 'Попросить счет', 'fr': 'Demander l\'addition', 'es': 'Pedir la cuenta', 'it': 'Chiedi il conto' },
  'Masayı Temizle': { 'en': 'Clean Table', 'de': 'Tisch reinigen', 'tr': 'Masayı Temizle', 'ar': 'نظف الطاولة', 'ru': 'Убрать со стола', 'fr': 'Nettoyer la table', 'es': 'Limpiar mesa', 'it': 'Pulisci tavolo' },
  'Yardım Gerekiyor': { 'en': 'Need Help', 'de': 'Hilfe benötigt', 'tr': 'Yardım Gerekiyor', 'ar': 'بحاجة للمساعدة', 'ru': 'Нужна помощь', 'fr': 'Besoin d\'aide', 'es': 'Necesito ayuda', 'it': 'Serve aiuto' },
  'Özel İstek': { 'en': 'Special Request', 'de': 'Sonderwunsch', 'tr': 'Özel İstek', 'ar': 'طلب خاص', 'ru': 'Особый запрос', 'fr': 'Demande spéciale', 'es': 'Solicitud especial', 'it': 'Richiesta speciale' },
  'İsteğinizi buraya yazın...': { 'en': 'Type your request here...', 'de': 'Geben Sie hier Ihre Anfrage ein...', 'tr': 'İsteğinizi buraya yazın...', 'ar': 'اكتب طلبك هنا...', 'ru': 'Введите ваш запрос здесь...', 'fr': 'Tapez votre demande ici...', 'es': 'Escribe tu solicitud aquí...', 'it': 'Scrivi qui la tua richiesta...' },
  'İstek Gönder': { 'en': 'Send Request', 'de': 'Anfrage senden', 'tr': 'İstek Gönder', 'ar': 'إرسال الطلب', 'ru': 'Отправить запрос', 'fr': 'Envoyer la demande', 'es': 'Enviar solicitud', 'it': 'Invia richiesta' },
  'Aktif İstekler': { 'en': 'Active Requests', 'de': 'Aktive Anfragen', 'tr': 'Aktif İstekler', 'ar': 'الطلبات النشطة', 'ru': 'Активные запросы', 'fr': 'Demandes actives', 'es': 'Solicitudes activas', 'it': 'Richieste attive' },

  // Dashboard Terms
  'Kontrol Paneli': { 'en': 'Dashboard', 'de': 'Dashboard', 'tr': 'Kontrol Paneli', 'ar': 'لوحة القيادة', 'ru': 'Панель управления', 'fr': 'Tableau de bord', 'es': 'Panel de control', 'it': 'Pannello di controllo' },
  'Hoş geldiniz': { 'en': 'Welcome', 'de': 'Willkommen', 'tr': 'Hoş geldiniz', 'ar': 'أهلا بك', 'ru': 'Добро пожаловать', 'fr': 'Bienvenue', 'es': 'Bienvenido', 'it': 'Benvenuto' },
  'Premium Plan': { 'en': 'Premium Plan', 'de': 'Premium-Plan', 'tr': 'Premium Plan', 'ar': 'خطة مميزة', 'ru': 'Премиум план', 'fr': 'Plan Premium', 'es': 'Plan Premium', 'it': 'Piano Premium' },
  'Bugünkü Siparişler': { 'en': 'Today\'s Orders', 'de': 'Heutige Bestellungen', 'tr': 'Bugünkü Siparişler', 'ar': 'طلبات اليوم', 'ru': 'Заказы сегодня', 'fr': 'Commandes d\'aujourd\'hui', 'es': 'Pedidos de hoy', 'it': 'Ordini di oggi' },
  'Bugünkü Ciro': { 'en': 'Today\'s Revenue', 'de': 'Heutiger Umsatz', 'tr': 'Bugünkü Ciro', 'ar': 'إيرادات اليوم', 'ru': 'Выручка сегодня', 'fr': 'Chiffre d\'affaires du jour', 'es': 'Ingresos de hoy', 'it': 'Entrate di oggi' },
  'Aktif durumda': { 'en': 'Active', 'de': 'Aktiv', 'tr': 'Aktif durumda', 'ar': 'نشط', 'ru': 'Активный', 'fr': 'Actif', 'es': 'Activo', 'it': 'Attivo' },
  'Artış trendi': { 'en': 'Upward trend', 'de': 'Aufwärtstrend', 'tr': 'Artış trendi', 'ar': 'اتجاه تصاعدي', 'ru': 'Восходящий тренд', 'fr': 'Tendance à la hausse', 'es': 'Tendencia al alza', 'it': 'Trend in crescita' },
  'Toplam Masa': { 'en': 'Total Tables', 'de': 'Tische gesamt', 'tr': 'Toplam Masa', 'ar': 'إجمالي الطاولات', 'ru': 'Всего столов', 'fr': 'Total des tables', 'es': 'Total mesas', 'it': 'Totale tavoli' },
  'Masa yönetimi aktif': { 'en': 'Table management active', 'de': 'Tischverwaltung aktiv', 'tr': 'Masa yönetimi aktif', 'ar': 'إدارة الجدول نشطة', 'ru': 'Управление столами активно', 'fr': 'Gestion des tables active', 'es': 'Gestión de mesas activa', 'it': 'Gestione tavoli attiva' },
  'Hızlı İşlemler': { 'en': 'Quick Actions', 'de': 'Schnellaktionen', 'tr': 'Hızlı İşlemler', 'ar': 'إجراءات سريعة', 'ru': 'Быстрые действия', 'fr': 'Actions rapides', 'es': 'Acciones rápidas', 'it': 'Azioni rapide' },
  'Yeni Ürün': { 'en': 'New Item', 'de': 'Neues Produkt', 'tr': 'Yeni Ürün', 'ar': 'عنصر جديد', 'ru': 'Новый товар', 'fr': 'Nouvel article', 'es': 'Nuevo artículo', 'it': 'Nuovo articolo' },
  'Siparişleri Gör': { 'en': 'View Orders', 'de': 'Bestellungen ansehen', 'tr': 'Siparişleri Gör', 'ar': 'عرض الطلبات', 'ru': 'Смотреть заказы', 'fr': 'Voir les commandes', 'es': 'Ver pedidos', 'it': 'Visualizza ordini' },
  'Menüyü Düzenle': { 'en': 'Edit Menu', 'de': 'Menü bearbeiten', 'tr': 'Menüyü Düzenle', 'ar': 'تعديل القائمة', 'ru': 'Редактировать меню', 'fr': 'Modifier le menu', 'es': 'Editar menú', 'it': 'Modifica menu' },
  'Duyurular (Aktif)': { 'en': 'Announcements (Active)', 'de': 'Ankündigungen (Aktiv)', 'tr': 'Duyurular (Aktif)', 'ar': 'الإعلانات (نشطة)', 'ru': 'Объявления (Активные)', 'fr': 'Annonces (Actives)', 'es': 'Anuncios (Activos)', 'it': 'Annunci (Attivi)' },
  'Aylık Performans': { 'en': 'Monthly Performance', 'de': 'Monatliche Leistung', 'tr': 'Aylık Performans', 'ar': 'الأداء الشهري', 'ru': 'Месячная эффективность', 'fr': 'Performance mensuelle', 'es': 'Rendimiento mensual', 'it': 'Performance mensile' },
  'Bu ay harika gidiyorsunuz! 🚀': { 'en': 'You are doing great this month! 🚀', 'de': 'Sie machen das diesen Monat großartig! 🚀', 'tr': 'Bu ay harika gidiyorsunuz! 🚀', 'ar': 'أنت تقوم بعمل رائع هذا الشهر! 🚀', 'ru': 'Отличная работа в этом месяце! 🚀', 'fr': 'Vous vous débrouillez très bien ce mois-ci ! 🚀', 'es': '¡Lo estás haciendo genial este mes! 🚀', 'it': 'Stai andando alla grande questo mese! 🚀' },
  'Henüz veri bulunmuyor 📊': { 'en': 'No data yet 📊', 'de': 'Noch keine Daten 📊', 'tr': 'Henüz veri bulunmuyor 📊', 'ar': 'لا توجد بيانات بعد 📊', 'ru': 'Данных пока нет 📊', 'fr': 'Pas encore de données 📊', 'es': 'Aún no hay datos 📊', 'it': 'Ancora nessun dato 📊' },
  'Aylık Ciro': { 'en': 'Monthly Revenue', 'de': 'Monatlicher Umsatz', 'tr': 'Aylık Ciro', 'ar': 'الإيرادات الشهرية', 'ru': 'Ежемесячная выручка', 'fr': 'Revenu mensuel', 'es': 'Ingresos mensuales', 'it': 'Entrate mensili' },
  'Toplam Sipariş': { 'en': 'Total Orders', 'de': 'Gesamtbestellungen', 'tr': 'Toplam Sipariş', 'ar': 'إجمالي الطلبات', 'ru': 'Всего заказов', 'fr': 'Commandes totales', 'es': 'Pedidos totales', 'it': 'Ordini totali' },
  'Ortalama Puan': { 'en': 'Average Rating', 'de': 'Durchschnittliche Bewertung', 'tr': 'Ortalama Puan', 'ar': 'متوسط التقييم', 'ru': 'Средний рейтинг', 'fr': 'Note moyenne', 'es': 'Calificación promedio', 'it': 'Valutazione media' },
  'Müşteri Memnuniyeti': { 'en': 'Customer Satisfaction', 'de': 'Kundenzufriedenheit', 'tr': 'Müşteri Memnuniyeti', 'ar': 'رضا العملاء', 'ru': 'Удовлетворенность клиентов', 'fr': 'Satisfaction client', 'es': 'Satisfacción del cliente', 'it': 'Soddisfazione del cliente' },

  // Sidebar Terms
  'Siparişler': { 'en': 'Orders', 'de': 'Bestellungen', 'tr': 'Siparişler', 'ar': 'الطلبات', 'ru': 'Заказы', 'fr': 'Commandes', 'es': 'Pedidos', 'it': 'Ordini' },
  'Menü Yönetimi': { 'en': 'Menu Management', 'de': 'Menüverwaltung', 'tr': 'Menü Yönetimi', 'ar': 'إدارة القائمة', 'ru': 'Управление меню', 'fr': 'Gestion du menu', 'es': 'Gestión de menú', 'it': 'Gestione menu' },
  'QR Kodlar': { 'en': 'QR Codes', 'de': 'QR-Codes', 'tr': 'QR Kodlar', 'ar': 'رموز الاستجابة السريعة', 'ru': 'QR-коды', 'fr': 'Codes QR', 'es': 'Códigos QR', 'it': 'Codici QR' },
  'Masa Yönetimi': { 'en': 'Table Management', 'de': 'Tischverwaltung', 'tr': 'Masa Yönetimi', 'ar': 'إدارة الجدول', 'ru': 'Управление столами', 'fr': 'Gestion des tables', 'es': 'Gestión de mesas', 'it': 'Gestione tavoli' },
  'Personel': { 'en': 'Staff', 'de': 'Personal', 'tr': 'Personel', 'ar': 'الموظفين', 'ru': 'Персонал', 'fr': 'Personnel', 'es': 'Personal', 'it': 'Personale' },
  'Raporlar': { 'en': 'Reports', 'de': 'Berichte', 'tr': 'Raporlar', 'ar': 'التقارير', 'ru': 'Отчеты', 'fr': 'Rapports', 'es': 'Informes', 'it': 'Rapporti' },
  'Ayarlar': { 'en': 'Settings', 'de': 'Einstellungen', 'tr': 'Ayarlar', 'ar': 'الإعدادات', 'ru': 'Настройки', 'fr': 'Paramètres', 'es': 'Ajustes', 'it': 'Impostazioni' },
  'Destek': { 'en': 'Support', 'de': 'Support', 'tr': 'Destek', 'ar': 'الدعم', 'ru': 'Поддержка', 'fr': 'Support', 'es': 'Soporte', 'it': 'Supporto' },
  'Stok Yönetimi': { 'en': 'Inventory Management', 'de': 'Bestandsverwaltung', 'tr': 'Stok Yönetimi', 'ar': 'إدارة المخزون', 'ru': 'Управление запасами', 'fr': 'Gestion des stocks', 'es': 'Gestión de inventario', 'it': 'Gestione inventario' },
  'Şube Yönetimi': { 'en': 'Branch Management', 'de': 'Filialverwaltung', 'tr': 'Şube Yönetimi', 'ar': 'إدارة الفروع', 'ru': 'Управление филиалами', 'fr': 'Gestion des succursales', 'es': 'Gestión de sucursales', 'it': 'Gestione filiali' },
  'API Yönetimi': { 'en': 'API Management', 'de': 'API-Verwaltung', 'tr': 'API Yönetimi', 'ar': 'إدارة API', 'ru': 'Управление API', 'fr': 'Gestion API', 'es': 'Gestión de API', 'it': 'Gestione API' },
  'Paket Servis': { 'en': 'Delivery', 'de': 'Lieferung', 'tr': 'Paket Servis', 'ar': 'توصيل', 'ru': 'Доставка', 'fr': 'Livraison', 'es': 'Entrega', 'it': 'Consegna' },
  'POS Entegrasyonu': { 'en': 'POS Integration', 'de': 'POS-Integration', 'tr': 'POS Entegrasyonu', 'ar': 'تكامل نقاط البيع', 'ru': 'Интеграция POS', 'fr': 'Intégration POS', 'es': 'Integración POS', 'it': 'Integrazione POS' },
  'Muhasebe': { 'en': 'Accounting', 'de': 'Buchhaltung', 'tr': 'Muhasebe', 'ar': 'محاسبة', 'ru': 'Бухгалтерия', 'fr': 'Comptabilité', 'es': 'Contabilidad', 'it': 'Contabilità' },
  'AI Önerileri': { 'en': 'AI Recommendations', 'de': 'KI-Empfehlungen', 'tr': 'AI Önerileri', 'ar': 'توصيات الذكاء الاصطناعي', 'ru': 'Рекомендации ИИ', 'fr': 'Recommandations IA', 'es': 'Recomendaciones de IA', 'it': 'Raccomandazioni AI' },
  'Video Menü': { 'en': 'Video Menu', 'de': 'Videomenü', 'tr': 'Video Menü', 'ar': 'قائمة الفيديو', 'ru': 'Видео меню', 'fr': 'Menu vidéo', 'es': 'Menú de video', 'it': 'Menu video' },
  'Etkinlikler': { 'en': 'Events', 'de': 'Veranstaltungen', 'tr': 'Etkinlikler', 'ar': 'الأحداث', 'ru': 'События', 'fr': 'Événements', 'es': 'Eventos', 'it': 'Eventi' },
  'Yönetim Paneli': { 'en': 'Management Panel', 'de': 'Verwaltungspanel', 'tr': 'Yönetim Paneli', 'ar': 'لوحة الإدارة', 'ru': 'Панель управления', 'fr': 'Panneau de gestion', 'es': 'Panel de gestión', 'it': 'Pannello di gestione' },
  'Çıkış Yap': { 'en': 'Logout', 'de': 'Abmelden', 'tr': 'Çıkış Yap', 'ar': 'تسجيل الخروج', 'ru': 'Выйти', 'fr': 'Se déconnecter', 'es': 'Cerrar sesión', 'it': 'Disconnettersi' },
  'Bugün': { 'en': 'Today', 'de': 'Heute', 'tr': 'Bugün', 'ar': 'اليوم', 'ru': 'Сегодня', 'fr': 'Aujourd\'hui', 'es': 'Hoy', 'it': 'Oggi' },
  'Tümünü Gör →': { 'en': 'See All →', 'de': 'Alle ansehen →', 'tr': 'Tümünü Gör →', 'ar': 'عرض الكل ←', 'ru': 'Смотреть все →', 'fr': 'Voir tout →', 'es': 'Ver todo →', 'it': 'Vedi tutto →' },
  'Hazır': { 'en': 'Ready', 'de': 'Bereit', 'tr': 'Hazır', 'ar': 'جاهز', 'ru': 'Готово', 'fr': 'Prêt', 'es': 'Listo', 'it': 'Pronto' },
  'Hazırlanıyor': { 'en': 'Preparing', 'de': 'Zubereitung', 'tr': 'Hazırlanıyor', 'ar': 'قيد الإعداد', 'ru': 'Готовится', 'fr': 'En préparation', 'es': 'Preparando', 'it': 'In preparazione' },
  'Kaldır': { 'en': 'Remove', 'de': 'Entfernen', 'tr': 'Kaldır', 'ar': 'إزالة', 'ru': 'Удалить', 'fr': 'Supprimer', 'es': 'Eliminar', 'it': 'Rimuovi' },
  'İstek gönderildi!': { 'en': 'Request sent!', 'de': 'Anfrage gesendet!', 'tr': 'İstek gönderildi!', 'ar': 'تم إرسال الطلب!', 'ru': 'Запрос отправлен!', 'fr': 'Demande envoyée !', 'es': '¡Solicitud enviada!', 'it': 'Richiesta inviata!' },
  'İsteğiniz garson ekibimize iletilecektir. En kısa sürede size yardımcı olacağız.': { 'en': 'Your request will be forwarded to our waiter team. We will help you as soon as possible.', 'de': 'Ihre Anfrage wird an unser Serviceteam weitergeleitet. Wir werden Ihnen so schnell wie möglich helfen.', 'tr': 'İsteğiniz garson ekibimize iletilecektir. En kısa sürede size yardımcı olacağız.', 'ar': 'سيتم إرسال طلبك إلى فريق النادل لدينا. سنساعدك في أقرب وقت ممكن.', 'ru': 'Ваш запрос будет передан нашей команде официантов. Мы поможем вам как можно скорее.', 'fr': 'Votre demande sera transmise à notre équipe de serveurs. Nous vous aiderons dès que possible.', 'es': 'Su solicitud será enviada a nuestro equipo de camareros. Le ayudaremos lo antes posible.', 'it': 'La tua richiesta verrà inoltrata al nostro team di camerieri. Ti aiuteremo il prima possibile.' },

  // New Terms for Menu Management
  'Durum': { 'en': 'Status', 'de': 'Status', 'tr': 'Durum' },
  'Tümü': { 'en': 'All', 'de': 'Alle', 'tr': 'Tümü' },
  'Mevcut': { 'en': 'Available', 'de': 'Vorhanden', 'tr': 'Mevcut' },
  'Tükendi': { 'en': 'Out of Stock', 'de': 'Ausverkauft', 'tr': 'Tükendi' },
  'Tükenen ürünleri göster': { 'en': 'Show out of stock items', 'de': 'Ausverkaufte Artikel anzeigen', 'tr': 'Tükenen ürünleri göster' },
  'Ürün': { 'en': 'Product', 'de': 'Produkt', 'tr': 'Ürün' },
  'Kategori': { 'en': 'Category', 'de': 'Kategorie', 'tr': 'Kategori' },
  'Detaylar': { 'en': 'Details', 'de': 'Details', 'tr': 'Detaylar' },
  'Fiyat': { 'en': 'Price', 'de': 'Preis', 'tr': 'Fiyat' },
  'İşlemler': { 'en': 'Actions', 'de': 'Aktionen', 'tr': 'İşlemler' },
  'Ara...': { 'en': 'Search...', 'de': 'Suchen...', 'tr': 'Ara...' },
  'Seçimi Temizle': { 'en': 'Clear Selection', 'de': 'Auswahl löschen', 'tr': 'Seçimi Temizle' },
  'ürün seçildi': { 'en': 'items selected', 'de': 'Elemente ausgewählt', 'tr': 'ürün seçildi' },
  'Fiyat Düzenle': { 'en': 'Edit Price', 'de': 'Preis bearbeiten', 'tr': 'Fiyat Düzenle' },
  'Sil': { 'en': 'Delete', 'de': 'Löschen', 'tr': 'Sil' },
  'Menü Kalemleri': { 'en': 'Menu Items', 'de': 'Menüartikel', 'tr': 'Menü Kalemleri' },
  'Kategoriler': { 'en': 'Categories', 'de': 'Kategorien', 'tr': 'Kategoriler' },
  'İstatistikler': { 'en': 'Statistics', 'de': 'Statistiken', 'tr': 'İstatistikler' },
  'Kategori Yok': { 'en': 'No Category', 'de': 'Keine Kategorie', 'tr': 'Kategori Yok' },
  'Alerjen': { 'en': 'Allergen', 'de': 'Allergene', 'tr': 'Alerjen' },
  'Malzemeler': { 'en': 'Ingredients', 'de': 'Zutaten', 'tr': 'Malzemeler' },
  'Aktif': { 'en': 'Active', 'de': 'Aktiv', 'tr': 'Aktif' },
  'Pasif': { 'en': 'Passive', 'de': 'Passiv', 'tr': 'Pasif' },
  'Backend verileri üzerinden hesaplanır': { 'en': 'Calculated via backend data', 'de': 'Wird über Backend-Daten berechnet', 'tr': 'Backend verileri üzerinden hesaplanır' },
  'Menü İstatistikleri': { 'en': 'Menu Statistics', 'de': 'Menüstatistiken', 'tr': 'Menü İstatistikleri' },
  'Toplam Ürün': { 'en': 'Total Items', 'de': 'Gesamtzahl Produkte', 'tr': 'Toplam Ürün' },
  'Popüler Ürünler': { 'en': 'Popular Items', 'de': 'Beliebte Produkte', 'tr': 'Popüler Ürünler' },
  'Kategori Sayısı': { 'en': 'Category Count', 'de': 'Anzahl Kategorien', 'tr': 'Kategori Sayısı' },
  'Ortalama Fiyat': { 'en': 'Average Price', 'de': 'Durchschnittspreis', 'tr': 'Ortalama Fiyat' },
  'Ürünü Düzenle': { 'en': 'Edit Item', 'de': 'Produkt bearbeiten', 'tr': 'Ürünü Düzenle' },
  'Yeni Ürün Ekle': { 'en': 'Add New Item', 'de': 'Neues Produkt hinzufügen', 'tr': 'Yeni Ürün Ekle' },
  'Ürün Adı *': { 'en': 'Product Name *', 'de': 'Produktname *', 'tr': 'Ürün Adı *' },
  'Açıklama': { 'en': 'Description', 'de': 'Beschreibung', 'tr': 'Açıklama' },
  'Çeviriler': { 'en': 'Translations', 'de': 'Übersetzungen', 'tr': 'Çeviriler' },
  'Seçili diller için ürün adı ve açıklamasını düzenleyin.': { 'en': 'Edit name and description for selected languages.', 'de': 'Namen und Beschreibung für ausgewählte Sprachen bearbeiten.', 'tr': 'Seçili diller için ürün adı ve açıklamasını düzenleyin.' },
  'Çevriliyor...': { 'en': 'Translating...', 'de': 'Wird übersetzt...', 'tr': 'Çevriliyor...' },
  'Otomatik Çevir': { 'en': 'Auto Translate', 'de': 'Automatisch übersetzen', 'tr': 'Otomatik Çevir' },
  'Fiyat (₺) *': { 'en': 'Price (₺) *', 'de': 'Preis (₺) *', 'tr': 'Fiyat (₺) *' },
  'Kategori *': { 'en': 'Category *', 'de': 'Kategorie *', 'tr': 'Kategori *' },
  'Kategori Seçin': { 'en': 'Select Category', 'de': 'Kategorie wählen', 'tr': 'Kategori Seçin' },
  'Önce kategori ekleyin': { 'en': 'Add category first', 'de': 'Zuerst Kategorie hinzufügen', 'tr': 'Önce kategori ekleyin' },
  'Kalori': { 'en': 'Calories', 'de': 'Kalorien', 'tr': 'Kalori' },
  'Hazırlık Süresi': { 'en': 'Prep Time', 'de': 'Zubereitungszeit', 'tr': 'Hazırlık Süresi' },
  'Hazırlık Süresi (dakika)': { 'en': 'Prep Time (minutes)', 'de': 'Zubereitungszeit (Minuten)', 'tr': 'Hazırlık Süresi (dakika)' },
  'Ürün Fotoğrafı': { 'en': 'Product Photo', 'de': 'Produktfoto', 'tr': 'Ürün Fotoğrafı' },
  'Kameradan Çek': { 'en': 'Take Photo', 'de': 'Foto aufnehmen', 'tr': 'Kameradan Çek' },
  'Dosyadan Yükle': { 'en': 'Upload File', 'de': 'Datei hochladen', 'tr': 'Dosyadan Yükle' },
  'dk': { 'en': 'min', 'de': 'Min', 'tr': 'dk' },
  'Düzenle': { 'en': 'Edit', 'de': 'Bearbeiten', 'tr': 'Düzenle' },
  'Yeni Kategori Ekle': { 'en': 'Add New Category', 'de': 'Neue Kategorie hinzufügen', 'tr': 'Yeni Kategori Ekle' },
  'Henüz kategori yok': { 'en': 'No categories yet', 'de': 'Noch keine Kategorien', 'tr': 'Henüz kategori yok' },
  'Menü ürünlerinizi düzenlemek için kategoriler oluşturun': { 'en': 'Create categories to organize your menu items', 'de': 'Erstellen Sie Kategorien, um Ihre Menüpunkte zu organisieren', 'tr': 'Menü ürünlerinizi düzenlemek için kategoriler oluşturun' },
  'İlk Kategoriyi Ekle': { 'en': 'Add First Category', 'de': 'Erste Kategorie hinzufügen', 'tr': 'İlk Kategoriyi Ekle' },
  'Gluten': { 'en': 'Gluten', 'de': 'Gluten', 'tr': 'Gluten' },
  'Süt': { 'en': 'Milk', 'de': 'Milch', 'tr': 'Süt' },
  'Yumurta': { 'en': 'Egg', 'de': 'Ei', 'tr': 'Yumurta' },
  'Fındık': { 'en': 'Hazelnut', 'de': 'Haselnuss', 'tr': 'Fındık' },
  'Fıstık': { 'en': 'Peanut', 'de': 'Erdnuss', 'tr': 'Fıstık' },
  'Soya': { 'en': 'Soy', 'de': 'Soja', 'tr': 'Soya' },
  'Balık': { 'en': 'Fish', 'de': 'Fisch', 'tr': 'Balık' },
  'Kabuklu Deniz Ürünleri': { 'en': 'Shellfish', 'de': 'Schalentiere', 'tr': 'Kabuklu Deniz Ürünleri' },
  'Dosya boyutu çok büyük. Maksimum 5MB olmalıdır.': { 'en': 'File size too large. Max 5MB.', 'de': 'Dateigröße zu groß. Max 5MB.', 'tr': 'Dosya boyutu çok büyük. Maksimum 5MB olmalıdır.' },
  'Lütfen sadece resim dosyası seçin.': { 'en': 'Please select only image files.', 'de': 'Bitte wählen Sie nur Bilddateien aus.', 'tr': 'Lütfen sadece resim dosyası seçin.' },
  'Resim başarıyla yüklendi!': { 'en': 'Image uploaded successfully!', 'de': 'Bild erfolgreich hochgeladen!', 'tr': 'Resim başarıyla yüklendi!' },
  'Resim yüklenemedi: ': { 'en': 'Image upload failed: ', 'de': 'Bild-Upload fehlgeschlagen: ', 'tr': 'Resim yüklenemedi: ' },
  'Resim yüklenirken hata oluştu: ': { 'en': 'Error uploading image: ', 'de': 'Fehler beim Hochladen des Bildes: ', 'tr': 'Resim yüklenirken hata oluştu: ' },
  'Telefon kamerası': { 'en': 'Phone camera', 'de': 'Handykamera', 'tr': 'Telefon kamerası' },
  'PNG, JPG, GIF': { 'en': 'PNG, JPG, GIF', 'de': 'PNG, JPG, GIF', 'tr': 'PNG, JPG, GIF' },
  'AI Görsel İşleme Aktif!': { 'en': 'AI Image Processing Active!', 'de': 'KI-Bildverarbeitung aktiv!', 'tr': 'AI Görsel İşleme Aktif!' },
  'Otomatik arka plan kaldırma': { 'en': 'Auto background removal', 'de': 'Automatische Hintergrundentfernung', 'tr': 'Otomatik arka plan kaldırma' },
  'Renk ve parlaklık optimizasyonu': { 'en': 'Color and brightness optimization', 'de': 'Farb- und Helligkeitsoptimierung', 'tr': 'Renk ve parlaklık optimizasyonu' },
  'Akıllı boyutlandırma': { 'en': 'Smart resizing', 'de': 'Intelligente Größenanpassung', 'tr': 'Akıllı boyutlandırma' },
  'Keskinlik artırma': { 'en': 'Sharpening', 'de': 'Schärfung', 'tr': 'Keskinlik artırma' },
  'Kameradan çekmek daha profesyonel sonuçlar verir': { 'en': 'Taking photo with camera gives professional results', 'de': 'Das Aufnehmen von Fotos mit der Kamera liefert professionellere Ergebnisse', 'tr': 'Kameradan çekmek daha profesyonel sonuçlar verir' },
  'Seçilen Fotoğraf:': { 'en': 'Selected Photo:', 'de': 'Ausgewähltes Foto:', 'tr': 'Seçilen Fotoğraf:' },
  'Ürün Durumu': { 'en': 'Product Status', 'de': 'Produktstatus', 'tr': 'Ürün Durumu' },
  'Popüler Ürün': { 'en': 'Popular Product', 'de': 'Beliebtes Produkt', 'tr': 'Popüler Ürün' },

  'Kaydet': { 'en': 'Save', 'de': 'Speichern', 'tr': 'Kaydet' },
  'Güncelle': { 'en': 'Update', 'de': 'Aktualisieren', 'tr': 'Güncelle' },
  'Ürün başarıyla güncellendi!': { 'en': 'Item updated successfully!', 'de': 'Produkt erfolgreich aktualisiert!', 'tr': 'Ürün başarıyla güncellendi!' },
  'Ürün güncellenirken bir hata oluştu: ': { 'en': 'Error occurred while updating item: ', 'de': 'Fehler beim Aktualisieren des Produkts: ', 'tr': 'Ürün güncellenirken bir hata oluştu: ' },
  'Lütfen ürün adı, fiyat ve kategori alanlarını doldurun!': { 'en': 'Please fill in product name, price and category fields!', 'de': 'Bitte füllen Sie die Felder Produktname, Preis und Kategorie aus!', 'tr': 'Lütfen ürün adı, fiyat ve kategori alanlarını doldurun!' },
  'Ürün başarıyla eklendi!': { 'en': 'Item added successfully!', 'de': 'Produkt erfolgreich hinzugefügt!', 'tr': 'Ürün başarıyla eklendi!' },
  'Ürün eklenirken bir hata oluştu: ': { 'en': 'Error occurred while adding item: ', 'de': 'Fehler beim Hinzufügen des Produkts: ', 'tr': 'Ürün eklenirken bir hata oluştu: ' },
  'Kategoriyi Düzenle': { 'en': 'Edit Category', 'de': 'Kategorie bearbeiten', 'tr': 'Kategoriyi Düzenle' },
  'Kategori Adı *': { 'en': 'Category Name *', 'de': 'Kategoriename *', 'tr': 'Kategori Adı *' },
  'Lütfen kategori adını girin!': { 'en': 'Please enter category name!', 'de': 'Bitte Kategoriename eingeben!', 'tr': 'Lütfen kategori adını girin!' },
  'Kategori işlemi sırasında bir hata oluştu: ': { 'en': 'Error occurred during category operation: ', 'de': 'Fehler bei der Kategorieoperation: ', 'tr': 'Kategori işlemi sırasında bir hata oluştu: ' },
  'Fotoğraf Çek': { 'en': 'Take Photo', 'de': 'Foto aufnehmen', 'tr': 'Fotoğraf Çek' },
  'Ürünü çerçeve içine alın': { 'en': 'Frame the product', 'de': 'Produkt einrahmen', 'tr': 'Ürünü çerçeve içine alın' },
  'Toplu Ürün İçe Aktar': { 'en': 'Bulk Product Import', 'de': 'Massenproduktimport', 'tr': 'Toplu Ürün İçe Aktar' },
  'CSV Formatı': { 'en': 'CSV Format', 'de': 'CSV-Format', 'tr': 'CSV Formatı' },
  'CSV dosyanız şu sütunları içermelidir:': { 'en': 'Your CSV file must include these columns:', 'de': 'Ihre CSV-Datei muss diese Spalten enthalten:', 'tr': 'CSV dosyanız şu sütunları içermelidir:' },
  'CSV Dosyası Yükle': { 'en': 'Upload CSV File', 'de': 'CSV-Datei hochladen', 'tr': 'CSV Dosyası Yükle' },
  'Tıklayın veya dosyayı sürükleyin': { 'en': 'Click or drag file', 'de': 'Klicken oder Datei ziehen', 'tr': 'Tıklayın veya dosyayı sürükleyin' },
  'Maksimum dosya boyutu: 5MB': { 'en': 'Max file size: 5MB', 'de': 'Maximale Dateigröße: 5MB', 'tr': 'Maksimum dosya boyutu: 5MB' },
  'Örnek Şablon': { 'en': 'Example Template', 'de': 'Beispielvorlage', 'tr': 'Örnek Şablon' },
  'Şablonu İndir': { 'en': 'Download Template', 'de': 'Vorlage herunterladen', 'tr': 'Şablonu İndir' },
  'Hızlı İçe Aktar': { 'en': 'Quick Import', 'de': 'Schnellimport', 'tr': 'Hızlı İçe Aktar' },
  'Yüzlerce ürünü tek seferde ekleyin': { 'en': 'Add hundreds of products at once', 'de': 'Hunderte Produkte auf einmal hinzufügen', 'tr': 'Yüzlerce ürünü tek seferde ekleyin' },
  'Otomatik Doğrulama': { 'en': 'Auto Validation', 'de': 'Automatische Validierung', 'tr': 'Otomatik Doğrulama' },
  'Hatalı veriler otomatik tespit edilir': { 'en': 'Invalid data is automatically detected', 'de': 'Ungültige Daten werden automatisch erkannt', 'tr': 'Hatalı veriler otomatik tespit edilir' },
  'CSV yükleme özelliği yakında aktif olacak! 🚀': { 'en': 'CSV upload feature coming soon! 🚀', 'de': 'CSV-Upload-Funktion kommt bald! 🚀', 'tr': 'CSV yükleme özelliği yakında aktif olacak! 🚀' },
  'Ürün Çevirileri': { 'en': 'Product Translations', 'de': 'Produktübersetzungen', 'tr': 'Ürün Çevirileri' },
  'Kapat': { 'en': 'Close', 'de': 'Schließen', 'tr': 'Kapat' },
  'Toplu Fiyat Düzenle': { 'en': 'Bulk Price Edit', 'de': 'Massenpreisbearbeitung', 'tr': 'Toplu Fiyat Düzenle' },
  'ürünün fiyatını güncelleyeceksiniz.': { 'en': 'products price will be updated.', 'de': 'Produktpreise werden aktualisiert.', 'tr': 'ürünün fiyatını güncelleyeceksiniz.' },
  'İşlem Türü': { 'en': 'Operation Type', 'de': 'Operationstyp', 'tr': 'İşlem Türü' },
  'Arttır': { 'en': 'Increase', 'de': 'Erhöhen', 'tr': 'Arttır' },
  'Azalt': { 'en': 'Decrease', 'de': 'Verringern', 'tr': 'Azalt' },
  'Değer Türü': { 'en': 'Value Type', 'de': 'Werttyp', 'tr': 'Değer Türü' },
  'Yüzde': { 'en': 'Percentage', 'de': 'Prozentsatz', 'tr': 'Yüzde' },
  '₺ Sabit': { 'en': '₺ Fixed', 'de': '₺ Fest', 'tr': '₺ Sabit' },
  'Değer': { 'en': 'Value', 'de': 'Wert', 'tr': 'Değer' },
  'Fiyatları %': { 'en': 'Prices %', 'de': 'Preise %', 'tr': 'Fiyatları %' },
  'Fiyatlara ₺': { 'en': 'Prices ₺', 'de': 'Preise ₺', 'tr': 'Fiyatlara ₺' },
  'ekle': { 'en': 'add', 'de': 'hinzufügen', 'tr': 'ekle' },
  'çıkar': { 'en': 'deduct', 'de': 'abziehen', 'tr': 'çıkar' },
  'arttır': { 'en': 'increase', 'de': 'erhöhen', 'tr': 'arttır' },
  'azalt': { 'en': 'decrease', 'de': 'verringern', 'tr': 'azalt' },



  // Orders Page Terms
  'Bekliyor': { 'en': 'Pending', 'de': 'Ausstehend', 'tr': 'Bekliyor' },
  'Teslim Edildi': { 'en': 'Delivered', 'de': 'Geliefert', 'tr': 'Teslim Edildi' },
  'Tamamlandı': { 'en': 'Completed', 'de': 'Abgeschlossen', 'tr': 'Tamamlandı' },
  'İptal Edildi': { 'en': 'Cancelled', 'de': 'Storniert', 'tr': 'İptal Edildi' },
  'Sipariş Detayları': { 'en': 'Order Details', 'de': 'Bestelldetails', 'tr': 'Sipariş Detayları' },
  'Sipariş Bilgileri': { 'en': 'Order Information', 'de': 'Bestellinformationen', 'tr': 'Sipariş Bilgileri' },
  'Masa No': { 'en': 'Table No', 'de': 'Tischnr.', 'tr': 'Masa No' },
  'Sipariş Zamanı': { 'en': 'Order Time', 'de': 'Bestellzeit', 'tr': 'Sipariş Zamanı' },
  'Müşteri': { 'en': 'Customer', 'de': 'Kunde', 'tr': 'Müşteri' },
  'Telefon': { 'en': 'Phone', 'de': 'Telefon', 'tr': 'Telefon' },
  'Toplam Tutar': { 'en': 'Total Amount', 'de': 'Gesamtbetrag', 'tr': 'Toplam Tutar' },
  'Ödeme Yöntemi': { 'en': 'Payment Method', 'de': 'Zahlungsmethode', 'tr': 'Ödeme Yöntemi' },
  'Sipariş Edilen Ürünler': { 'en': 'Ordered Items', 'de': 'Bestellte Artikel', 'tr': 'Sipariş Edilen Ürünler' },
  'Özel Notlar': { 'en': 'Special Notes', 'de': 'Besondere Hinweise', 'tr': 'Özel Notlar' },
  'Aktif Çağrılar': { 'en': 'Active Calls', 'de': 'Aktive Anrufe', 'tr': 'Aktif Çağrılar' },
  'Rapor İndir': { 'en': 'Download Report', 'de': 'Bericht herunterladen', 'tr': 'Rapor İndir' },
  'Yazdır': { 'en': 'Print', 'de': 'Drucken', 'tr': 'Yazdır' },
  'Sipariş bulunamadı': { 'en': 'No orders found', 'de': 'Keine Bestellungen gefunden', 'tr': 'Sipariş bulunamadı' },
  'Filtreleri değiştirerek tekrar deneyin': { 'en': 'Try changing filters', 'de': 'Versuchen Sie, die Filter zu ändern', 'tr': 'Filtreleri değiştirerek tekrar deneyin' },
  'Tüm Durumlar': { 'en': 'All Statuses', 'de': 'Alle Status', 'tr': 'Tüm Durumlar' },
  'Bu Hafta': { 'en': 'This Week', 'de': 'Diese Woche', 'tr': 'Bu Hafta' },
  'Bu Ay': { 'en': 'This Month', 'de': 'Diesen Monat', 'tr': 'Bu Ay' },
  'Dün': { 'en': 'Yesterday', 'de': 'Gestern', 'tr': 'Dün' },
  'En Yeni': { 'en': 'Newest', 'de': 'Neueste', 'tr': 'En Yeni' },
  'En Eski': { 'en': 'Oldest', 'de': 'Älteste', 'tr': 'En Eski' },
  'Bekleme Süresi': { 'en': 'Waiting Time', 'de': 'Wartezeit', 'tr': 'Bekleme Süresi' },
  'Tutar': { 'en': 'Amount', 'de': 'Betrag', 'tr': 'Tutar' },
  'Garson çağrısı': { 'en': 'Waiter Call', 'de': 'Kellnerruf', 'tr': 'Garson çağrısı' },
  'Su isteniyor': { 'en': 'Water Requested', 'de': 'Wasser gewünscht', 'tr': 'Su isteniyor' },
  'Hesap isteniyor': { 'en': 'Bill Requested', 'de': 'Rechnung gewünscht', 'tr': 'Hesap isteniyor' },
  'Masa temizleme isteniyor': { 'en': 'Cleaning Requested', 'de': 'Reinigung gewünscht', 'tr': 'Masa temizleme isteniyor' },
  'Müşteri adı, masa no veya ürün ara...': { 'en': 'Search customer, table no or item...', 'de': 'Kunde, Tischnr. oder Artikel suchen...', 'tr': 'Müşteri adı, masa no veya ürün ara...' },
  'Tüm siparişleri görüntüleyin ve yönetin': { 'en': 'View and manage all orders', 'de': 'Alle Bestellungen anzeigen und verwalten', 'tr': 'Tüm siparişleri görüntüleyin ve yönetin' },
  'Sipariş Değeri': { 'en': 'Order Value', 'de': 'Bestellwert', 'tr': 'Sipariş Değeri' },

  // QR Codes Page Terms
  'QR Kod Yönetimi': { 'en': 'QR Code Management', 'de': 'QR-Code-Verwaltung', 'tr': 'QR Kod Yönetimi' },
  'Masa QR kodlarınızı oluşturun ve yönetin': { 'en': 'Create and manage your table QR codes', 'de': 'Erstellen und verwalten Sie Ihre Tisch-QR-Codes', 'tr': 'Masa QR kodlarınızı oluşturun ve yönetin' },
  'QR Kod Oluştur': { 'en': 'Create QR Code', 'de': 'QR-Code erstellen', 'tr': 'QR Kod Oluştur' },
  'Toplam QR Kod': { 'en': 'Total QR Codes', 'de': 'Gesamte QR-Codes', 'tr': 'Toplam QR Kod' },
  'Aktif Kodlar': { 'en': 'Active Codes', 'de': 'Aktive Codes', 'tr': 'Aktif Kodlar' },
  'Toplam Tarama': { 'en': 'Total Scans', 'de': 'Gesamtscans', 'tr': 'Toplam Tarama' },
  'QR Kodlarım': { 'en': 'My QR Codes', 'de': 'Meine QR-Codes', 'tr': 'QR Kodlarım' },
  'Henüz QR kod yok': { 'en': 'No QR codes yet', 'de': 'Noch keine QR-Codes', 'tr': 'Henüz QR kod yok' },
  'İlk QR kodunuzu oluşturmak için başlayın': { 'en': 'Start by creating your first QR code', 'de': 'Beginnen Sie mit der Erstellung Ihres ersten QR-Codes', 'tr': 'İlk QR kodunuzu oluşturmak için başlayın' },
  'URL Kopyala': { 'en': 'Copy URL', 'de': 'URL kopieren', 'tr': 'URL Kopyala' },
  'QR Kodunu İndir': { 'en': 'Download QR Code', 'de': 'QR-Code herunterladen', 'tr': 'QR Kodunu İndir' },
  'Token oluşturulamadı': { 'en': 'Token could not be created', 'de': 'Token konnte nicht erstellt werden', 'tr': 'Token oluşturulamadı' },
  'Token oluşturma hatası': { 'en': 'Token creation error', 'de': 'Fehler bei der Tokenerstellung', 'tr': 'Token oluşturma hatası' },
  'Token oluşturulurken hata oluştu': { 'en': 'Error occurred while creating token', 'de': 'Fehler beim Erstellen des Tokens', 'tr': 'Token oluşturulurken hata oluştu' },
  'QR kod oluşturma hatası': { 'en': 'QR code creation error', 'de': 'Fehler bei der QR-Code-Erstellung', 'tr': 'QR kod oluşturma hatası' },
  'QR kod oluşturulurken hata oluştu': { 'en': 'Error occurred while creating QR code', 'de': 'Fehler beim Erstellen des QR-Codes', 'tr': 'QR kod oluşturulurken hata oluştu' },
  'adet QR kod başarıyla oluşturuldu!': { 'en': 'QR codes created successfully!', 'de': 'QR-Codes erfolgreich erstellt!', 'tr': 'adet QR kod başarıyla oluşturuldu!' },
  'QR kod silindi.': { 'en': 'QR code deleted.', 'de': 'QR-Code gelöscht.', 'tr': 'QR kod silindi.' },
  'URL kopyalandı!': { 'en': 'URL copied!', 'de': 'URL kopiert!', 'tr': 'URL kopyalandı!' },
  'URL kopyalanamadı': { 'en': 'URL could not be copied', 'de': 'URL konnte nicht kopiert werden', 'tr': 'URL kopyalanamadı' },
  'QR kodlar yükleniyor...': { 'en': 'Loading QR codes...', 'de': 'QR-Codes werden geladen...', 'tr': 'QR kodlar yükleniyor...' },
  'Yükleniyor...': { 'en': 'Loading...', 'de': 'Wird geladen...', 'tr': 'Yükleniyor...' },
  'Masa Sayısı': { 'en': 'Table Count', 'de': 'tischanzahl', 'tr': 'Masa Sayısı' },
  '1 ile 50 arasında masa sayısı seçebilirsiniz': { 'en': 'You can select between 1 and 50 tables', 'de': 'Sie können zwischen 1 und 50 Tischen wählen', 'tr': '1 ile 50 arasında masa sayısı seçebilirsiniz' },
  'Oluşturuluyor...': { 'en': 'Creating...', 'de': 'Wird erstellt...', 'tr': 'Oluşturuluyor...' },
  'Oluştur': { 'en': 'Create', 'de': 'Erstellen', 'tr': 'Oluştur' },
  'Masa': { 'en': 'Table', 'de': 'Tisch', 'tr': 'Masa' },
  'için QR kod': { 'en': 'QR code for', 'de': 'QR-Code für', 'tr': 'için QR kod' },
  '- QR Menü': { 'en': '- QR Menu', 'de': '- QR-Menü', 'tr': '- QR Menü' },
  'Restoran bilgisi bulunamadı!': { 'en': 'Restaurant info not found!', 'de': 'Imbiss-Informationen nicht gefunden!', 'tr': 'Restoran bilgisi bulunamadı!' },

  // Settings Page Terms
  'İşletme ayarlarınızı yönetin': { 'en': 'Manage your business settings', 'de': 'Verwalten Sie Ihre Geschäftseinstellungen', 'tr': 'İşletme ayarlarınızı yönetin' },
  'Duyurular': { 'en': 'Announcements', 'de': 'Ankündigungen', 'tr': 'Duyurular' },
  'Genel Ayarlar': { 'en': 'General Settings', 'de': 'Allgemeine Einstellungen', 'tr': 'Genel Ayarlar' },
  'Görsel Kimlik': { 'en': 'Visual Identity', 'de': 'Visuelle Identität', 'tr': 'Görsel Kimlik' },
  'Diller': { 'en': 'Languages', 'de': 'Sprachen', 'tr': 'Diller' },
  'MasApp\'e Hoş Geldiniz!': { 'en': 'Welcome to MasApp!', 'de': 'Willkommen bei MasApp!', 'tr': 'MasApp\'e Hoş Geldiniz!' },
  'İşletmenizi MasApp ile dijitalleştirin.': { 'en': 'Digitize your business with MasApp.', 'de': 'Digitalisieren Sie Ihr Geschäft mit MasApp.', 'tr': 'İşletmenizi MasApp ile dijitalleştirin.' },
  'QR Kod Menü': { 'en': 'QR Code Menu', 'de': 'QR-Code-Menü', 'tr': 'QR Kod Menü' },
  'Mutfak Paneli': { 'en': 'Kitchen Panel', 'de': 'Küchenpanel', 'tr': 'Mutfak Paneli' },
  'Garson Paneli': { 'en': 'Waiter Panel', 'de': 'Kellnerpanel', 'tr': 'Garson Paneli' },
  'İşletme Bilgileri': { 'en': 'Business Information', 'de': 'Geschäftsinformationen', 'tr': 'İşletme Bilgileri' },
  'İşletme Adı *': { 'en': 'Business Name *', 'de': 'Geschäftsname *', 'tr': 'İşletme Adı *' },
  'İşletme Türü *': { 'en': 'Business Type *', 'de': 'Geschäftstyp *', 'tr': 'İşletme Türü *' },
  'Cafe & Kahvehane': { 'en': 'Cafe & Coffee Shop', 'de': 'Café & Kaffeehaus', 'tr': 'Cafe & Kahvehane' },
  'Restoran': { 'en': 'Restaurant', 'de': 'Restaurant', 'tr': 'Restoran' },
  'Fast Food': { 'en': 'Fast Food', 'de': 'Fast Food', 'tr': 'Fast Food' },
  'Bar & Pub': { 'en': 'Bar & Pub', 'de': 'Bar & Pub', 'tr': 'Bar & Pub' },
  'Fırın & Pastane': { 'en': 'Bakery & Patisserie', 'de': 'Bäckerei & Konditorei', 'tr': 'Fırın & Pastane' },
  'Pizzeria': { 'en': 'Pizzeria', 'de': 'Pizzeria', 'tr': 'Pizzeria' },
  'İşletme türü menü tasarımını ve özelliklerini etkiler.': { 'en': 'Business type affects menu design and features.', 'de': 'Der Geschäftstyp beeinflusst das Menüdesign und die Funktionen.', 'tr': 'İşletme türü menü tasarımını ve özelliklerini etkiler.' },
  'Subdomain': { 'en': 'Subdomain', 'de': 'Subdomain', 'tr': 'Subdomain' },
  'Menü adresiniz:': { 'en': 'Your menu address:', 'de': 'Ihre Menüadresse:', 'tr': 'Menü adresiniz:' },
  'Açıklama': { 'en': 'Description', 'de': 'Beschreibung', 'tr': 'Açıklama' },
  'Slogan': { 'en': 'Slogan', 'de': 'Slogan', 'tr': 'Slogan' },
  'İletişim Bilgileri': { 'en': 'Contact Information', 'de': 'Kontaktinformationen', 'tr': 'İletişim Bilgileri' },
  'Adres': { 'en': 'Address', 'de': 'Adresse', 'tr': 'Adres' },
  'Web Sitesi': { 'en': 'Website', 'de': 'Webseite', 'tr': 'Web Sitesi' },
  'WiFi Şifresi': { 'en': 'WiFi Password', 'de': 'WLAN-Passwort', 'tr': 'WiFi Şifresi' },
  'WiFi Şifresini Kaydet': { 'en': 'Save WiFi Password', 'de': 'WLAN-Passwort speichern', 'tr': 'WiFi Şifresini Kaydet' },
  'Menüde WiFi şifresini göster': { 'en': 'Show WiFi password in menu', 'de': 'WLAN-Passwort im Menü anzeigen', 'tr': 'Menüde WiFi şifresini göster' },
  'Çalışma Saatleri (7 Gün)': { 'en': 'Working Hours (7 Days)', 'de': 'Öffnungszeiten (7 Tage)', 'tr': 'Çalışma Saatleri (7 Gün)' },
  'Çalışma Saatlerini Kaydet': { 'en': 'Save Working Hours', 'de': 'Öffnungszeiten speichern', 'tr': 'Çalışma Saatlerini Kaydet' },
  'Menüde çalışma saatlerini göster': { 'en': 'Show working hours in menu', 'de': 'Öffnungszeiten im Menü anzeigen', 'tr': 'Menüde çalışma saatlerini göster' },
  'Çalışma saatleri menünün alt kısmında gösterilecektir.': { 'en': 'Working hours will be shown at the bottom of the menu.', 'de': 'Öffnungszeiten werden unten im Menü angezeigt.', 'tr': 'Çalışma saatleri menünün alt kısmında gösterilecektir.' },
  'Menü Özel İçerikler': { 'en': 'Menu Special Content', 'de': 'Spezielle Menüinhalte', 'tr': 'Menü Özel İçerikler' },
  'Müşteri menüsünde gösterilen günlük duyurular ve özel içerikler': { 'en': 'Daily announcements and special content shown in customer menu', 'de': 'Tägliche Ankündigungen und spezielle Inhalte im Kundenmenü', 'tr': 'Müşteri menüsünde gösterilen günlük duyurular ve özel içerikler' },
  'Bugüne Özel Başlık': { 'en': 'Today\'s Special Title', 'de': 'Titel des Tages', 'tr': 'Bugüne Özel Başlık' },
  'Detaylı Açıklama': { 'en': 'Detailed Description', 'de': 'Detaillierte Beschreibung', 'tr': 'Detaylı Açıklama' },
  'Günün Çorbası Başlık': { 'en': 'Soup of the Day Title', 'de': 'Suppe des Tages Titel', 'tr': 'Günün Çorbası Başlık' },
  'Çorba İsmi ve Açıklama': { 'en': 'Soup Name and Description', 'de': 'Suppenname und Beschreibung', 'tr': 'Çorba İsmi ve Açıklama' },
  'Bu içerikler müşteri menüsünün en üstünde slider olarak gösterilecektir.': { 'en': 'These contents will be shown as a slider at the top of the customer menu.', 'de': 'Diese Inhalte werden als Slider oben im Kundenmenü angezeigt.', 'tr': 'Bu içerikler müşteri menüsünün en üstünde slider olarak gösterilecektir.' },
  'Sosyal Medya Linkleri': { 'en': 'Social Media Links', 'de': 'Social Media Links', 'tr': 'Sosyal Medya Linkleri' },
  'Instagram Linkini Kaydet': { 'en': 'Save Instagram Link', 'de': 'Instagram-Link speichern', 'tr': 'Instagram Linkini Kaydet' },
  'Menüde Instagram linkini göster': { 'en': 'Show Instagram link in menu', 'de': 'Instagram-Link im Menü anzeigen', 'tr': 'Menüde Instagram linkini göster' },
  'Durum': { 'en': 'Status', 'de': 'Status', 'tr': 'Durum' },
  'Aktif': { 'en': 'Active', 'de': 'Aktiv', 'tr': 'Aktif' },
  'Pasif': { 'en': 'Inactive', 'de': 'Inaktiv', 'tr': 'Pasif' },
  'Pasif durumda menü görüntülenmeyecektir.': { 'en': 'Menu will not be displayed in inactive status.', 'de': 'Im inaktiven Zustand wird das Menü nicht angezeigt.', 'tr': 'Pasif durumda menü görüntülenmeyecektir.' },
  'Logo (Splash Ekranı)': { 'en': 'Logo (Splash Screen)', 'de': 'Logo (Startbildschirm)', 'tr': 'Logo (Splash Ekranı)' },
  'Logo sadece uygulama açılış ekranında (splash) görünür. Menü tasarımında logo gösterilmez.': { 'en': 'Logo only appears on app splash screen. It is not shown in menu design.', 'de': 'Logo erscheint nur auf dem App-Startbildschirm. Es wird nicht im Menüdesign angezeigt.', 'tr': 'Logo sadece uygulama açılış ekranında (splash) görünür. Menü tasarımında logo gösterilmez.' },
  'Logoyu Değiştir': { 'en': 'Change Logo', 'de': 'Logo ändern', 'tr': 'Logoyu Değiştir' },
  'Logo Yükle': { 'en': 'Upload Logo', 'de': 'Logo hochladen', 'tr': 'Logo Yükle' },
  'Logo yüklemek için tıklayın': { 'en': 'Click to upload logo', 'de': 'Klicken zum Hochladen des Logos', 'tr': 'Logo yüklemek için tıklayın' },
  'Menü Renk Paleti': { 'en': 'Menu Color Palette', 'de': 'Menü-Farbpalette', 'tr': 'Menü Renk Paleti' },
  'Seçtiğiniz renkler menü tasarımında butonlar, kategoriler ve vurgular için kullanılır.': { 'en': 'Selected colors are used for buttons, categories and highlights in menu design.', 'de': 'Ausgewählte Farben werden für Schaltflächen, Kategorien und Hervorhebungen im Menüdesign verwendet.', 'tr': 'Seçtiğiniz renkler menü tasarımında butonlar, kategoriler ve vurgular için kullanılır.' },
  'Ana Renk': { 'en': 'Primary Color', 'de': 'Primärfarbe', 'tr': 'Ana Renk' },
  'İkinci Renk': { 'en': 'Secondary Color', 'de': 'Sekundärfarbe', 'tr': 'İkinci Renk' },
  'Arka plan ve vurgu renkleri otomatik hesaplanacak': { 'en': 'Background and accent colors will be calculated automatically', 'de': 'Hintergrund- und Akzentfarben werden automatisch berechnet', 'tr': 'Arka plan ve vurgu renkleri otomatik hesaplanacak' },
  'Font Ayarları': { 'en': 'Font Settings', 'de': 'Schrifteinstellungen', 'tr': 'Font Ayarları' },
  'Font Ailesi': { 'en': 'Font Family', 'de': 'Schriftart', 'tr': 'Font Ailesi' },
  'Menüde kullanılacak font ailesi': { 'en': 'Font family to be used in menu', 'de': 'Schriftart für das Menü', 'tr': 'Menüde kullanılacak font ailesi' },
  'Temel Font Boyutu': { 'en': 'Base Font Size', 'de': 'Basis-Schriftgröße', 'tr': 'Temel Font Boyutu' },
  'Temel metin boyutu': { 'en': 'Base text size', 'de': 'Basis-Textgröße', 'tr': 'Temel metin boyutu' },
  'Küçük': { 'en': 'Small', 'de': 'Klein', 'tr': 'Küçük' },
  'Orta': { 'en': 'Medium', 'de': 'Mittel', 'tr': 'Orta' },
  'Büyük': { 'en': 'Large', 'de': 'Groß', 'tr': 'Büyük' },
  'Stil Ayarları': { 'en': 'Style Settings', 'de': 'Stileinstellungen', 'tr': 'Stil Ayarları' },
  'Header Stili': { 'en': 'Header Style', 'de': 'Header-Stil', 'tr': 'Header Stili' },
  'Gradyan': { 'en': 'Gradient', 'de': 'Verlauf', 'tr': 'Gradyan' },
  'Düz': { 'en': 'Solid', 'de': 'Vollton', 'tr': 'Düz' },
  'Çerçeveli': { 'en': 'Outlined', 'de': 'Umrandet', 'tr': 'Çerçeveli' },
  'Minimal': { 'en': 'Minimal', 'de': 'Minimal', 'tr': 'Minimal' },
  'Sayfa başlığının görünüm stili': { 'en': 'Appearance style of page header', 'de': 'Erscheinungsbild des Seitenkopfes', 'tr': 'Sayfa başlığının görünüm stili' },
  'Canlı Önizleme': { 'en': 'Live Preview', 'de': 'Live-Vorschau', 'tr': 'Canlı Önizleme' },
  'Değişikliklerinizi anlık olarak görüntüleyin': { 'en': 'View your changes instantly', 'de': 'Sehen Sie Ihre Änderungen sofort', 'tr': 'Değişikliklerinizi anlık olarak görüntüleyin' },
  'Aç': { 'en': 'Open', 'de': 'Öffnen', 'tr': 'Aç' },
  'Yenile': { 'en': 'Refresh', 'de': 'Aktualisieren', 'tr': 'Yenile' },
  'Canlı Önizleme Aktif': { 'en': 'Live Preview Active', 'de': 'Live-Vorschau Aktiv', 'tr': 'Canlı Önizleme Aktif' },
  'Değişiklikleriniz anında yansıtılır': { 'en': 'Your changes are reflected instantly', 'de': 'Ihre Änderungen werden sofort übernommen', 'tr': 'Değişiklikleriniz anında yansıtılır' },
  'Dil Ayarları': { 'en': 'Language Settings', 'de': 'Spracheinstellungen', 'tr': 'Dil Ayarları' },
  'Menüde göstermek istediğiniz dilleri seçin. En az bir dil aktif olmalıdır.': { 'en': 'Select languages to show in menu. At least one language must be active.', 'de': 'Wählen Sie Sprachen für das Menü. Mindestens eine Sprache muss aktiv sein.', 'tr': 'Menüde göstermek istediğiniz dilleri seçin. En az bir dil aktif olmalıdır.' },
  'Aktif Dil:': { 'en': 'Active Language:', 'de': 'Aktive Sprache:', 'tr': 'Aktif Dil:' },
  'Varsayılan Dil': { 'en': 'Default Language', 'de': 'Standardsprache', 'tr': 'Varsayılan Dil' },
  'Müşteriler menüyü açtığında ilk görecekleri dili seçin.': { 'en': 'Select the language customers see first when they open the menu.', 'de': 'Wählen Sie die Sprache, die Kunden beim Öffnen des Menüs zuerst sehen.', 'tr': 'Müşteriler menüyü açtığında ilk görecekleri dili seçin.' },
  'Varsayılan': { 'en': 'Default', 'de': 'Standard', 'tr': 'Varsayılan' },
  'Dil çevirileri otomatik olarak oluşturulur. Menüde seçtiğiniz diller arasında geçiş yapılabilir.': { 'en': 'Language translations are generated automatically. You can switch between languages in the menu.', 'de': 'Sprachübersetzungen werden automatisch erstellt. Im Menü kann zwischen Sprachen gewechselt werden.', 'tr': 'Dil çevirileri otomatik olarak oluşturulur. Menüde seçtiğiniz diller arasında geçiş yapılabilir.' },
  'Ödeme Bilgileri': { 'en': 'Payment Information', 'de': 'Zahlungsinformationen', 'tr': 'Ödeme Bilgileri' },
  'Ödeme bilgileriniz güvenli bir şekilde saklanmaktadır.': { 'en': 'Your payment information is stored securely.', 'de': 'Ihre Zahlungsinformationen werden sicher gespeichert.', 'tr': 'Ödeme bilgileriniz güvenli bir şekilde saklanmaktadır.' },
  'Ödeme bilgileri için lütfen bizimle iletişime geçin.': { 'en': 'Please contact us for payment information.', 'de': 'Bitte kontaktieren Sie uns für Zahlungsinformationen.', 'tr': 'Ödeme bilgileri için lütfen bizimle iletişime geçin.' },
  'Hemen Arayın': { 'en': 'Call Now', 'de': 'Jetzt anrufen', 'tr': 'Hemen Arayın' },
  'Entegrasyonlar': { 'en': 'Integrations', 'de': 'Integrationen', 'tr': 'Entegrasyonlar' },
  'POS Sistemleri': { 'en': 'POS Systems', 'de': 'POS-Systeme', 'tr': 'POS Sistemleri' },
  'Muhasebe': { 'en': 'Accounting', 'de': 'Buchhaltung', 'tr': 'Muhasebe' },
  'Online Ödeme': { 'en': 'Online Payment', 'de': 'Online-Zahlung', 'tr': 'Online Ödeme' },
  'Stok Yönetimi': { 'en': 'Inventory Management', 'de': 'Bestandsverwaltung', 'tr': 'Stok Yönetimi' },
  'CRM Sistemleri': { 'en': 'CRM Systems', 'de': 'CRM-Systeme', 'tr': 'CRM Sistemleri' },
  'Rezervasyon': { 'en': 'Reservation', 'de': 'Reservierung', 'tr': 'Rezervasyon' },
  'Bağla': { 'en': 'Connect', 'de': 'Verbinden', 'tr': 'Bağla' },
  'Yakında': { 'en': 'Coming Soon', 'de': 'Demnächst', 'tr': 'Yakında' },
  'Bildirim Ayarları': { 'en': 'Notification Settings', 'de': 'Benachrichtigungseinstellungen', 'tr': 'Bildirim Ayarları' },
  'E-posta Bildirimleri': { 'en': 'Email Notifications', 'de': 'E-Mail-Benachrichtigungen', 'tr': 'E-posta Bildirimleri' },
  'Yeni siparişler': { 'en': 'New orders', 'de': 'Neue Bestellungen', 'tr': 'Yeni siparişler' },
  'Günlük raporlar': { 'en': 'Daily reports', 'de': 'Tägliche Berichte', 'tr': 'Günlük raporlar' },
  'Sistem güncellemeleri': { 'en': 'System updates', 'de': 'Systemupdates', 'tr': 'Sistem güncellemeleri' },
  'SMS Bildirimleri': { 'en': 'SMS Notifications', 'de': 'SMS-Benachrichtigungen', 'tr': 'SMS Bildirimleri' },
  'Premium Özellik': { 'en': 'Premium Feature', 'de': 'Premium-Funktion', 'tr': 'Premium Özellik' },
  'SMS bildirimleri Premium plan ile kullanılabilir.': { 'en': 'SMS notifications available with Premium plan.', 'de': 'SMS-Benachrichtigungen sind im Premium-Plan verfügbar.', 'tr': 'SMS bildirimleri Premium plan ile kullanılabilir.' },
  'Sadece bugün geçerli': { 'en': 'Valid only today', 'de': 'Nur heute gültig', 'tr': 'Sadece bugün geçerli' },
  'Ev yapımı lezzet': { 'en': 'Homemade taste', 'de': 'Hausgemachter Geschmack', 'tr': 'Ev yapımı lezzet' },
  'Subdomain en az 3 karakter olmalıdır': { 'en': 'Subdomain must be at least 3 characters', 'de': 'Subdomain muss mindestens 3 Zeichen lang sein', 'tr': 'Subdomain en az 3 karakter olmalıdır' },
  'Kontrol ediliyor...': { 'en': 'Checking...', 'de': 'Überprüfung...', 'tr': 'Kontrol ediliyor...' },
  'Subdomain kullanılabilir': { 'en': 'Subdomain available', 'de': 'Subdomain verfügbar', 'tr': 'Subdomain kullanılabilir' },
  'Bu subdomain zaten kullanımda': { 'en': 'This subdomain is already in use', 'de': 'Diese Subdomain ist bereits vergeben', 'tr': 'Bu subdomain zaten kullanımda' },
  'Kontrol sırasında hata oluştu': { 'en': 'Error occurred during check', 'de': 'Fehler bei der Überprüfung', 'tr': 'Kontrol sırasında hata oluştu' },
  'En az bir dil aktif olmalı.': { 'en': 'At least one language must be active.', 'de': 'Mindestens eine Sprache muss aktiv sein.', 'tr': 'En az bir dil aktif olmalı.' },

  // Dashboard Plans & Services
  'Küçük ve orta ölçekli işletmeler için': { 'en': 'For small and medium businesses', 'de': 'Für kleine und mittlere Unternehmen', 'tr': 'Küçük ve orta ölçekli işletmeler için' },
  'Kurumsal Paket': { 'en': 'Corporate Plan', 'de': 'Unternehmensplan', 'tr': 'Kurumsal Paket' },
  'Büyük işletmeler ve zincirler için': { 'en': 'For large enterprises and chains', 'de': 'Für Großunternehmen und Ketten', 'tr': 'Büyük işletmeler ve zincirler için' },
  'QR Menü Sistemi (Sınırsız menü, anlık güncelleme)': { 'en': 'QR Menu System (Unlimited menu, instant updates)', 'de': 'QR-Menüsystem (Unbegrenztes Menü, sofortige Updates)', 'tr': 'QR Menü Sistemi (Sınırsız menü, anlık güncelleme)' },
  'Mutfak Paneli (5 kullanıcı, sipariş takibi)': { 'en': 'Kitchen Panel (5 users, order tracking)', 'de': 'Küchenpanel (5 Benutzer, Auftragsverfolgung)', 'tr': 'Mutfak Paneli (5 kullanıcı, sipariş takibi)' },
  'Müşteri Uygulaması (Sipariş verme, ödeme)': { 'en': 'Customer App (Ordering, payment)', 'de': 'Kunden-App (Bestellung, Zahlung)', 'tr': 'Müşteri Uygulaması (Sipariş verme, ödeme)' },
  '7/24 WhatsApp Destek': { 'en': '24/7 WhatsApp Support', 'de': '24/7 WhatsApp-Support', 'tr': '7/24 WhatsApp Destek' },
  'Google Yorum Entegrasyonu': { 'en': 'Google Review Integration', 'de': 'Google-Bewertungsintegration', 'tr': 'Google Yorum Entegrasyonu' },
  'Detaylı Satış Raporları': { 'en': 'Detailed Sales Reports', 'de': 'Detaillierte Verkaufsberichte', 'tr': 'Detaylı Satış Raporları' },
  'Mobil Uyumlu Tasarım': { 'en': 'Mobile Responsive Design', 'de': 'Mobilfreundliches Design', 'tr': 'Mobil Uyumlu Tasarım' },
  'Sınırsız Kullanıcı (Tüm paneller)': { 'en': 'Unlimited Users (All panels)', 'de': 'Unbegrenzte Benutzer (Alle Panels)', 'tr': 'Sınırsız Kullanıcı (Tüm paneller)' },
  'Çoklu Şube Yönetimi': { 'en': 'Multi-Branch Management', 'de': 'Mehrfilialen-Management', 'tr': 'Çoklu Şube Yönetimi' },
  'Özel Menü ve Logo Entegrasyonu': { 'en': 'Custom Menu and Logo Integration', 'de': 'Individuelles Menü und Logo-Integration', 'tr': 'Özel Menü ve Logo Entegrasyonu' },
  'Özel Tema Tasarımı': { 'en': 'Custom Theme Design', 'de': 'Individuelles Theme-Design', 'tr': 'Özel Tema Tasarımı' },
  'API Entegrasyonları (POS, Muhasebe)': { 'en': 'API Integrations (POS, Accounting)', 'de': 'API-Integrationen (POS, Buchhaltung)', 'tr': 'API Entegrasyonları (POS, Muhasebe)' },
  'Özel Eğitim ve Danışmanlık': { 'en': 'Special Training and Consulting', 'de': 'Spezialtraining und Beratung', 'tr': 'Özel Eğitim ve Danışmanlık' },
  'Öncelikli WhatsApp Destek': { 'en': 'Priority WhatsApp Support', 'de': 'Priorisierter WhatsApp-Support', 'tr': 'Öncelikli WhatsApp Destek' },
  'Gelişmiş Analitik ve Raporlama': { 'en': 'Advanced Analytics and Reporting', 'de': 'Erweiterte Analytik und Berichterstattung', 'tr': 'Gelişmiş Analitik ve Raporlama' },
  'Özel Geliştirmeler': { 'en': 'Custom Developments', 'de': 'Individuelle Entwicklungen', 'tr': 'Özel Geliştirmeler' },
  'Dedicated Account Manager': { 'en': 'Dedicated Account Manager', 'de': 'Dedizierter Account Manager', 'tr': 'Dedicated Account Manager' },
  '7/24 Telefon Desteği': { 'en': '24/7 Phone Support', 'de': '24/7 Telefonsupport', 'tr': '7/24 Telefon Desteği' },
  'Özel Rapor Şablonları': { 'en': 'Custom Report Templates', 'de': 'Benutzerdefinierte Berichtsvorlagen', 'tr': 'Özel Rapor Şablonları' },
  'Beyaz Etiket Çözümü': { 'en': 'White Label Solution', 'de': 'White-Label-Lösung', 'tr': 'Beyaz Etiket Çözümü' },
  'Menü Özelleştirme': { 'en': 'Menu Customization', 'de': 'Menüanpassung', 'tr': 'Menü Özelleştirme' },
  'Özel tema, logo ve tasarım değişiklikleri': { 'en': 'Custom theme, logo and design changes', 'de': 'Individuelles Theme, Logo und Designänderungen', 'tr': 'Özel tema, logo ve tasarım değişiklikleri' },
  'QR Kod Tasarımı': { 'en': 'QR Code Design', 'de': 'QR-Code-Design', 'tr': 'QR Kod Tasarımı' },
  'Özel QR kod tasarımı ve yerleşimi': { 'en': 'Custom QR code design and placement', 'de': 'Individuelles QR-Code-Design und Platzierung', 'tr': 'Özel QR kod tasarımı ve yerleşimi' },
  'Rapor Özelleştirme': { 'en': 'Report Customization', 'de': 'Berichtsanpassung', 'tr': 'Rapor Özelleştirme' },
  'Özel rapor şablonları ve analitik': { 'en': 'Custom report templates and analytics', 'de': 'Benutzerdefinierte Berichtsvorlagen und Analytik', 'tr': 'Özel rapor şablonları ve analitik' },
  'Personel Eğitimi': { 'en': 'Staff Training', 'de': 'Personalschulung', 'tr': 'Personel Eğitimi' },
  'Panel kullanımı ve sistem eğitimi': { 'en': 'Panel usage and system training', 'de': 'Panelnutzung und Systemschulung', 'tr': 'Panel kullanımı ve sistem eğitimi' },
  'Sipariş Entegrasyonu': { 'en': 'Order Integration', 'de': 'Bestellintegration', 'tr': 'Sipariş Entegrasyonu' },
  'POS ve ödeme sistem entegrasyonu': { 'en': 'POS and payment system integration', 'de': 'POS- und Zahlungssystemintegration', 'tr': 'POS ve ödeme sistem entegrasyonu' },
  'Çoklu Şube Kurulumu': { 'en': 'Multi-Branch Setup', 'de': 'Mehrfilialen-Einrichtung', 'tr': 'Çoklu Şube Kurulumu' },
  'Ek şube ekleme ve yönetimi': { 'en': 'Adding and managing extra branches', 'de': 'Hinzufügen und Verwalten zusätzlicher Filialen', 'tr': 'Ek şube ekleme ve yönetimi' },
  'Ödeme Başarılı! 🎉': { 'en': 'Payment Successful! 🎉', 'de': 'Zahlung erfolgreich! 🎉', 'tr': 'Ödeme Başarılı! 🎉' },
  'Planınız aktifleştirildi!': { 'en': 'Your plan has been activated!', 'de': 'Ihr Plan wurde aktiviert!', 'tr': 'Planınız aktifleştirildi!' },
  'Ödeme Yap': { 'en': 'Pay', 'de': 'Bezahlen', 'tr': 'Ödeme Yap' },
  'Dilediğiniz ek hizmet hangi paneldeyse hemen sepete ekleyin. Birden fazla seçebilirsiniz. Örneğin mutfak panelinde kaç tane değişiklik istiyorsanız o kadar sayı seçebilirsiniz, fiyat ona göre eklenecektir.': {
    'en': 'Add any additional service you want to your cart from its respective panel. You can select multiple. For example, select as many changes as you want in the kitchen panel, price will be added accordingly.',
    'de': 'Fügen Sie jeden gewünschten zusätzlichen Service aus dem jeweiligen Panel Ihrem Warenkorb hinzu. Sie können mehrere auswählen. Zum Beispiel wählen Sie so viele Änderungen, wie Sie im Küchenpanel wünschen, der Preis wird entsprechend hinzugefügt.',
    'tr': 'Dilediğiniz ek hizmet hangi paneldeyse hemen sepete ekleyin. Birden fazla seçebilirsiniz. Örneğin mutfak panelinde kaç tane değişiklik istiyorsanız o kadar sayı seçebilirsiniz, fiyat ona göre eklenecektir.'
  },
  'Sonraki ödeme': { 'en': 'Next payment', 'de': 'Nächste Zahlung', 'tr': 'Sonraki ödeme' },
  'Faturalandırma Dönemini Değiştir': { 'en': 'Change Billing Cycle', 'de': 'Rechnungszeitraum ändern', 'tr': 'Faturalandırma Dönemini Değiştir' },
  'Faturalandırma döneminizi değiştirerek tasarruf edebilirsiniz': { 'en': 'Save by changing your billing cycle', 'de': 'Sparen Sie durch Ändern Ihres Rechnungszeitraums', 'tr': 'Faturalandırma döneminizi değiştirerek tasarruf edebilirsiniz' },
  'Her ay ödeme': { 'en': 'Pay monthly', 'de': 'Monatliche Zahlung', 'tr': 'Her ay ödeme' },
  '%17 indirim': { 'en': '17% discount', 'de': '17% Rabatt', 'tr': '%17 indirim' },
  '%20 indirim': { 'en': '20% discount', 'de': '20% Rabatt', 'tr': '%20 indirim' },
  'Sepetiniz': { 'en': 'Your Cart', 'de': 'Ihr Warenkorb', 'tr': 'Sepetiniz' },
  'Paket ve Hizmet Yönetimi': { 'en': 'Package and Service Management', 'de': 'Paket- und Serviceverwaltung', 'tr': 'Paket ve Hizmet Yönetimi' },
  'İhtiyacınıza göre plan ve ek hizmetler seçin': { 'en': 'Choose plans and extra services according to your needs', 'de': 'Wählen Sie Pläne und Zusatzleistungen nach Ihren Bedürfnissen', 'tr': 'İhtiyacınıza göre plan ve ek hizmetler seçin' },
  'Aylık': { 'en': 'Monthly', 'de': 'Monatlich', 'tr': 'Aylık' },
  '6 Aylık': { 'en': '6 Months', 'de': '6 Monate', 'tr': '6 Aylık' },
  'Yıllık': { 'en': 'Yearly', 'de': 'Jährlich', 'tr': 'Yıllık' },
  'ödeme': { 'en': 'payment', 'de': 'Zahlung', 'tr': 'ödeme' },
  'Mevcut Planınız': { 'en': 'Your Current Plan', 'de': 'Ihr aktueller Plan', 'tr': 'Mevcut Planınız' },
  'Ek Hizmetler': { 'en': 'Additional Services', 'de': 'Zusätzliche Dienstleistungen', 'tr': 'Ek Hizmetler' },
};

interface TranslatedTextProps {
  children: string;
  className?: string;
  as?: keyof JSX.IntrinsicElements;
}

export default function TranslatedText({
  children,
  className = '',
  as: Component = 'span'
}: TranslatedTextProps) {
  const { translate, currentLanguage } = useLanguage();
  const [translatedText, setTranslatedText] = useState(children);
  const [isLoading, setIsLoading] = useState(false);
  const [isClient, setIsClient] = useState(false);

  // Set client-side flag to prevent hydration issues
  useEffect(() => {
    setIsClient(true);
  }, []);

  useEffect(() => {
    if (!isClient) return; // Only run on client side

    const translateContent = async () => {
      // Check static dictionary first
      const langCode = currentLanguage === 'German' ? 'de' :
        (currentLanguage === 'English' ? 'en' :
          (currentLanguage === 'Turkish' ? 'tr' :
            (currentLanguage === 'Arabic' ? 'ar' :
              (currentLanguage === 'Russian' ? 'ru' :
                (currentLanguage === 'French' ? 'fr' :
                  (currentLanguage === 'Spanish' ? 'es' :
                    (currentLanguage === 'Italian' ? 'it' : 'en')))))));

      if (staticDictionary[children] && staticDictionary[children][langCode]) {
        // console.log(`Using static translation for "${children}": ${staticDictionary[children][langCode]}`);
        setTranslatedText(staticDictionary[children][langCode]);
        return;
      }

      if (currentLanguage === 'Turkish') {
        setTranslatedText(children);
        return;
      }

      setIsLoading(true);
      try {
        const translated = await translate(children);
        setTranslatedText(translated);
      } catch (error) {
        console.error('Translation failed:', error);
        setTranslatedText(children);
      } finally {
        setIsLoading(false);
      }
    };

    translateContent();
  }, [children, currentLanguage, translate, isClient]);

  return (
    <Component className={`${className} ${isLoading ? 'opacity-70' : ''}`}>
      {translatedText}
    </Component>
  );
}
